### ISSUE TITLE
Fails to build with Clang due to -Werror=unused-but-set-variable

### ISSUE THREAD

**Issue by jbeich** [phkaeser/wlmaker#53]
Regressed by #47

```c
$ export CC=clang
$ cmake -G Ninja
$ cmake --build .
[...]
src/conf/grammar.c:1243:9: error: variable 'yynerrs' set but not used [-Werror,-Wunused-but-set-variable]
 1243 |     int yynerrs = 0;
      |         ^
```

**Comment by phkaeser** [comment]
https://mail.gnu.org/archive/html/bison-patches/2022-08/msg00006.html

**Comment by phkaeser** [comment]
Above #54 suppresses the warning temporarily, as it's coming from bison and reported by recent clang. That should fix the build breakage.

(Will have to revert that eventually, once bison versions catch up over stable distros)
